# Generated by Django 2.2.3 on 2019-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191012_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='file',
        ),
        migrations.AddField(
            model_name='job',
            name='github',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
