# Generated by Django 3.0.2 on 2020-02-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191012_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Kobe', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
