# Generated by Django 2.2 on 2019-05-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190510_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
